### ISSUE TITLE
State sync crashed 

### ISSUE THREAD

**Issue by liangping** [CosmosContracts/juno#172]
```
3:40PM INF Applied snapshot chunk to ABCI app chunk=34 format=1 height=2425000 module=statesync total=35
3:40PM INF Verified ABCI app appHash="��C�<l\x15�M��'��q�;�\x16\x05�|2���A�\x17��x" height=2425000 module=statesync
3:40PM INF Snapshot restored format=1 hash="Px^Y+S�\x1f�X�\x1a�W>�n\x01h᯿r,\x10s����\"�" height=2425000 module=statesync
3:40PM INF Starting BlockPool service impl=BlockPool module=blockchain
3:40PM INF minted coins from module account amount=5142792ujuno from=mint module=x/bank
3:40PM INF executed block height=2425001 module=state num_invalid_txs=0 num_valid_txs=0
3:40PM INF commit synced commit=436F6D6D697449447B5B35302037362032382031373420313233203130342036312037372031333020323339203133382031333120313430203232352031313420333820323520353020323438203538203235203138382031393120323334203939203233362033342031373620313820313637203137392037345D3A3235303041397D
3:40PM INF committed state app_hash=324C1CAE7B683D4D82EF8A838CE172261932F83A19BCBFEA63EC22B012A7B34A height=2425001 module=state num_txs=0
3:40PM INF indexed block height=2425001 module=txindex

...

3:40PM INF executed block height=2425002 module=state num_invalid_txs=3 num_valid_txs=17
3:40PM INF commit synced commit=436F6D6D697449447B5B313537203133302031323020313834203136312033322031343120313220313832203136372036382036332032333120323338203831203234392037352031353520353020343720373520323337203135352037362031343920393520333320313333203234382031353320323036203232315D3A3235303041417D
3:40PM INF committed state app_hash=9D8278B8A1208D0CB6A7443FE7EE51F94B9B322F4BED9B4C955F2185F899CEDD height=2425002 module=state num_txs=20
3:40PM INF indexed block height=2425002 module=txindex
panic: Failed to process committed block (2425003:47C9A3DD169701894478B9061D8DBD9D12BFC39FD32111B6B731B4BE5AFBB9C3): wrong Block.Header.AppHash.  Expected 9D8278B8A1208D0CB6A7443FE7EE51F94B9B322F4BED9B4C955F2185F899CEDD, got 1C57CEE2170211ECEAC9AE5461AB7CE3AA86E77EA1BD92449DF600BC84C73D0E

goroutine 666 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0001d4540, 0x1)
	github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:401 +0x123a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	github.com/tendermint/tendermint@v0.34.15/blockchain/v0/reactor.go:125 +0xe5
```

Both sides are using the same version:
```
~/go/bin/junod version --long
name: juno
server_name: junod
version: v2.1.0
commit: e6b8c212b178cf575035065b78309aed547b1335
build_tags: netgo,ledger
go: go version go1.18 linux/amd64
```

**Comment by giansalex** [comment]
Juno doesn't support state-sync in the normal way, see [polkachu state-sync](https://polkachu.com/state_sync/juno) , pending issue #29
