### ISSUE TITLE
 startup node service reported an error

### ISSUE THREAD

**Issue by Liamlu28** [CosmosContracts/juno#266]
When I replaced the synchronized Juno main network data directory, the startup node service reported an error, and the source node did not start verification services. I don't use a validator.how should i solve it
```
juno@chart-1660385642-0:/tmp$ junod start
3:17AM INF starting node with ABCI Tendermint in-process
3:17AM INF Starting multiAppConn service impl=multiAppConn module=proxy
3:17AM INF Starting localClient service connection=query impl=localClient module=abci-client
3:17AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
3:17AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
3:17AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
3:17AM INF Starting EventBus service impl=EventBus module=events
3:17AM INF Starting PubSub service impl=PubSub module=pubsub
3:17AM INF Starting IndexerService service impl=IndexerService module=txindex
3:17AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v9.0.0
3:17AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
3:17AM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/nonnegative-outstanding
3:17AM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/can-withdraw
3:17AM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/reference-count
3:17AM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/module-account
3:17AM INF asserting crisis invariants inv=5/11 module=x/crisis name=staking/module-accounts
3:17AM INF asserting crisis invariants inv=6/11 module=x/crisis name=staking/nonnegative-power
3:17AM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/positive-delegation
3:17AM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/delegator-shares
3:17AM INF asserting crisis invariants inv=9/11 module=x/crisis name=gov/module-account
3:17AM INF asserting crisis invariants inv=10/11 module=x/crisis name=bank/nonnegative-outstanding
3:17AM INF asserting crisis invariants inv=11/11 module=x/crisis name=bank/total-supply
3:17AM INF asserted all invariants duration=219.645742 height=0 module=x/crisis
panic: commission can't be lower than 5%: unauthorized

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.DeliverGenTxs({{0x29e8328, 0xc00013e300}, {0x29f5b80, 0xc0011cdd00}, {{0x0, 0x0}, {0xc000f32108, 0x6}, 0x0, {0x0, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.6/x/genutil/gentx.go:113 +0x274
github.com/cosmos/cosmos-sdk/x/genutil.InitGenesis(...)
	github.com/cosmos/cosmos-sdk@v0.45.6/x/genutil/genesis.go:18
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{}, {_, _}, {_, _}, _, {_, _}}, {{0x29e8328, 0xc00013e300}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.6/x/genutil/module.go:99 +0x15e
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x29e8328, 0xc00013e300}, {0x29f5b80, 0xc0011cdd00}, {{0x0, 0x0}, {0xc000f32108, 0x6}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.6/types/module/module.go:320 +0x29d
github.com/CosmosContracts/juno/v9/app.(*App).InitChainer(_, {{0x29e8328, 0xc00013e300}, {0x29f5b80, 0xc0011cdd00}, {{0x0, 0x0}, {0xc000f32108, 0x6}, 0x0, ...}, ...}, ...)
	github.com/CosmosContracts/juno/v9/app/app.go:697 +0x20e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000583380, {{0x0, 0xed8e91970, 0x0}, {0xc000f32108, 0x6}, 0xc000e86fc0, {0x3a8a418, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.6/baseapp/abci.go:62 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000f35260, {{0x0, 0xed8e91970, 0x0}, {0xc000f32108, 0x6}, 0xc000e86fc0, {0x3a8a418, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0x0, 0xed8e91970, 0x0}, {0xc000f32108, 0x6}, 0xc000e86fc0, {0x3a8a418, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x29c3548, 0x8}}, {0xc000f32108, 0x6}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0088edf80, {0x29f6f00, 0xc000f1e000})
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x29c3548, 0x8}}, {0xc000f32108, 0x6}, 0x1, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc00128edc0, {0x29e4a70, 0xc000f11180}, 0xc00106e430, {0x29cb2c0, 0xc00000e780}, 0x0?, 0x0?, 0xc00106e9c0, {0x29e95c0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x29fdc00, 0xc00139aed0}, {0x0, 0x0}, {0x29ecb38, 0xc000248690}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0012c2a00?, {0x3a8a418?, 0x0?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.45.6/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0012c2a00, {0x3a8a418, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00024b900)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2761c50?, {0xc00013fbc0, 0xb})
	github.com/cosmos/cosmos-sdk@v0.45.6/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/CosmosContracts/juno/v9/cmd/junod/main.go:24 +0x7c
```

**Comment by faddat** [comment]
https://github.com/CosmosContracts/juno/blob/main/scripts/statesync.bash

**Comment by ironxyz** [comment]
> https://github.com/CosmosContracts/juno/blob/main/scripts/statesync.bash

I found this link because I am using the latest version v9.0.0 @faddat So I have to restore from snapshot?
https://github.com/CosmosContracts/Juno/issues/160
