### ISSUE TITLE
Feeshare: issues occur if protos are rebuilt

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#438]
Discovered by:

```bash
bash scripts/protocgen.sh
```

Log:

```
panic: concrete type *types.MsgRegisterFeeShare has already been registered under typeURL /, cannot register *types.MsgCancelFeeShare under same typeURL. This usually means that there are conflicting modules registering different concrete types for a same interface implementation [recovered]
        panic: concrete type *types.MsgRegisterFeeShare has already been registered under typeURL /, cannot register *types.MsgCancelFeeShare under same typeURL. This usually means that there are conflicting modules registering different concrete types for a same interface implementation
```

Theory:

code changed and protos did not, or vice versa.  So now when protos get rebuilt things explode some.

**Comment by faddat** [comment]
Hopefully resolved by #439

**Comment by faddat** [comment]
two tests are failing:

```
--- FAIL: TestGenesisTestSuite (0.01s)
    --- FAIL: TestGenesisTestSuite/TestFeeShareInitGenesis (0.01s)
        suite.go:77: test panicked: parameter FeePercentage not registered
            goroutine 9 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
            github.com/stretchr/testify/suite.failOnPanic(0x140005656c0, {0x101fce920, 0x14000e30830})
```


```
--- FAIL: TestKeeperTestSuite (0.03s)
    --- FAIL: TestKeeperTestSuite/TestCancelFeeShare (0.01s)
        suite.go:77: test panicked: parameter FeePercentage not registered
            goroutine 26 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
            github.com/stretchr/testify/suite.failOnPanic(0x14000583040, {0x102a4ab40, 0x14000ed6be0})
```

**Comment by faddat** [comment]
@Reecepbcups / @vuong177 if you feel that this is now resolved, could you just note the root cause and close?  thanks!

**Comment by Reecepbcups** [comment]
Test "parameter FeePercentage not registered" failing was due to the PacketForwardMiddleware not being registered in the init params keeper function

Then protos switched from cosmos proto to gogoproto/proto since feeshare uses messages & not just queries (like the mint module)
